# Site settings
# These are used to personalize your new site.
title: Melody Cabanellas # your name here
logo: "/images/headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Arts in Applied Computing: Graphic Arts Concentration (class of 2026)
  <br /><br />
  <a href="/pdf/Resume.pdf">View My Resume</a>
 
repository: "mcabane/mcabane.github.io"
github_username:  mcabane # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

